### ISSUE TITLE
I'd love to see an example usage...

### ISSUE THREAD

**Issue by shutej** [tekerson/purescript-websocket#1]
I'm a n00b, but a dedicated one, and I can't quite figure out how to wire it together such that it works.

**Comment by tekerson** [comment]
Yeah, for sure.

I should probably have written some documentation. I was planning on improving the API, but haven't got round to it.

This is probably the simplest thing that works - it connects to `ws://127.0.0.1:1337` and `console.log`/`trace`s the messages it receives.

``` purescript
module Main where

import HTML5.WebSocket

import Control.Monad.Eff (Eff ())
import Control.Monad.Trans (lift)
import Data.Either (Either (Left, Right))
import Debug.Trace (Trace (..), trace)


main :: forall eff. Eff (ws :: WS, trace :: Trace | eff) Unit
main = do
  trace "START"
  runWebSocket $ do
    result <- withWebSocket config handlers
    case result of
         Right _ -> output "DONE"
         Left err -> output err

config =
  { uri: "ws://127.0.0.1:1337"
  , protocols: []
  }

handlers :: forall eff. WebSocketHandler (trace :: Trace | eff)
handlers s = (defaultHandlers s)
  { onOpen = onOpenHandler
  , onMessage = onMessageHandler
  }

onOpenHandler :: forall eff. WithWebSocket (trace :: Trace | eff) Unit
onOpenHandler = trace "OPEN"

onMessageHandler :: forall eff. String -> WithWebSocket (trace :: Trace | eff) Unit
onMessageHandler msg = trace msg

output :: forall eff. String -> WebSocket (trace :: Trace | eff) Unit
output = lift <<< trace
```

**Comment by shutej** [comment]
Just wanted to say thanks for this.  It's particularly helpful to me that you added the type signatures.  I'm going to do a bit of unification by hand to work my way through what's actually going on here.

(I got very confused around ContT in the implementation.)

**Comment by tekerson** [comment]
Example added to in #5
