### ISSUE TITLE
Are the dependencies out of date?

### ISSUE THREAD

**Issue by AKST** [tekerson/purescript-websocket#3]
When I compile I get the following compiler error

```
Error in module Data.Foldable
Cannot import unknown module 'Data.Eq'
```

And it looks like the version of `purescript-transformers` is not up too date. I would try figure this myself and make a PR, but I'm relatively new to purescript myself & haven't had much luck figuring out a fix

edit: more detail & spelling

**Comment by tekerson** [comment]
They are indeed, due to a change in the Prelude (https://github.com/purescript/purescript/issues/769).

I've bumped the purescript-transformers version just enough so that it should build with the latest Prelude.

It still needs looking at, but let me know if that helps.

**Comment by AKST** [comment]
Thanks! I'll let you know as soon as I try it out

**Comment by AKST** [comment]
Update, it compiles!

**Comment by tekerson** [comment]
Awesome, I'm working on some changes.
So I'll do a more thorough dependency review with that. And hopefully an example (Not sure when that'll be though).
